"""empty message

Revision ID: 2d34487c211a
Revises: 1166034b5983
Create Date: 2024-05-17 17:54:16.789843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d34487c211a'
down_revision = '1166034b5983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarefa_usuario',
    sa.Column('tarefa_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tarefa_id'], ['tarefas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tarefa_usuario')
    # ### end Alembic commands ###
